[package]
name = "libnvme-c"
version = "0.1.0"
authors = ["Gris Ge <fge@redhat.com>"]

[lib]
name = "nvme"
path = "lib.rs"
crate-type = ["cdylib"]

[dependencies]
nvme-mgmt = { path = "../nvme" }
libc = "0.2.32"
