[package]
name = "nvme"
description = "NVMe Management Rust Interface"
version = "0.1.0"
authors = ["Gris Ge <fge@redhat.com>"]

[lib]
name = "nvme"
path = "lib.rs"
crate-type = ["lib"]

[dependencies]
nix = "0.9.0"
byteorder = "1.1.0"
libc = "0.2.32"
regex = "0.2.2"
