[package]
name = "nmc"
description = "NVMe Management CLI"
version = "0.1.0"
authors = ["Gris Ge <fge@redhat.com>"]

[[bin]]
name = "nmc"
path = "nmc.rs"

[dependencies]
nvme = { path = "../nvme" }
prettytable-rs = "0.6.7"
